development:
  adapter: postgresql
  encoding: unicode
  database: flixsterpals_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: flixsterpals_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: flixsterpals_production
  pool: 5
  username: flixsterpals
  password:
